database:
  uri: "mongodb+srv://yeneinehseiba:<db_password>@lamebora.hlmxq.mongodb.net/?retryWrites=true&w=majority&appName=LameBora"
  # uri: "mongodb://localhost:27017"
  name: "Loan"
email:
  key: "ftau bsae lmkp gvqd"
  sender: "yeneineh.seiba@a2sv.org"
port: "http://localhost:8080"
jwt:
  jwtKey: "yenesecret"
